# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-17 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_squares', models.IntegerField()),
                ('assigned_squares', django_mysql.models.ListCharField(models.CharField(max_length=2), max_length=300, size=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('accepted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squares Accepted',
                'verbose_name_plural': 'Squares Accepted',
            },
        ),
        migrations.CreateModel(
            name='SquaresProposed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=256)),
                ('team_b', models.CharField(max_length=256)),
                ('per_square_cost', models.IntegerField()),
                ('remaining_squares', models.IntegerField(default=100)),
                ('end_date', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
                ('assigned_squares', models.TextField()),
                ('use_shit_payout', models.BooleanField()),
                ('q1_winning_square', models.IntegerField()),
                ('q2_winning_square', models.IntegerField()),
                ('q3_winning_square', models.IntegerField()),
                ('q4_winning_square', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('q1_winning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1_winning_user', to=settings.AUTH_USER_MODEL)),
                ('q2_winning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q2_winning_user', to=settings.AUTH_USER_MODEL)),
                ('q3_winning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q3_winning_user', to=settings.AUTH_USER_MODEL)),
                ('q4_winning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q4_winning_user', to=settings.AUTH_USER_MODEL)),
                ('shit_22_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shit_22_user', to=settings.AUTH_USER_MODEL)),
                ('shit_55_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shit_55_user', to=settings.AUTH_USER_MODEL)),
                ('shit_99_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shit_99_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Squares Proposed',
                'verbose_name_plural': 'Squares Proposed',
            },
        ),
        migrations.AddField(
            model_name='squaresaccepted',
            name='squares_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squares.SquaresProposed'),
        ),
    ]
