# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-18 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squaresproposed',
            old_name='per_square_cost',
            new_name='price_per_square',
        ),
    ]
