# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models

class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0003_auto_20181218_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresaccepted',
            name='assigned_squares',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2), blank=True, max_length=300, null=True, size=100),
        ),
    ]
