# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposedBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_text', models.CharField(max_length=256)),
                ('prop_wager', models.IntegerField()),
                ('max_wagers', models.IntegerField()),
                ('remaining_wagers', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('won_bet', models.IntegerField(choices=[(1, 'Win'), (-1, 'Loss'), (0, 'Tie')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.IntegerField(default=0, help_text="The user's current balance. Every time the user settles up, the current balance is reset to zero.")),
                ('overall_winnings', models.IntegerField(default=0, help_text="The user's overall winnings since joining.")),
                ('get_site_emails', models.BooleanField(default=True)),
                ('last_payment', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_current_balance', models.IntegerField()),
                ('new_current_balance', models.IntegerField()),
                ('original_overall_winnings', models.IntegerField()),
                ('new_overall_winnings', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('accepted_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.AcceptedBet')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_admin', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acceptedbet',
            name='accepted_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.ProposedBet'),
        ),
        migrations.AddField(
            model_name='acceptedbet',
            name='accepted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
