# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedbet',
            name='won_bet',
            field=models.IntegerField(blank=True, choices=[(1, 'Win'), (-1, 'Loss'), (0, 'Tie')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
