# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20161224_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedbet',
            options={'verbose_name': 'Accepted Bet'},
        ),
        migrations.AlterModelOptions(
            name='proposedbet',
            options={'ordering': ['end_date'], 'verbose_name': 'Proposed Bet'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='userprofileaudit',
            options={'verbose_name': 'User Profile Audit'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='get_site_emails',
            new_name='get_accepted_bet_emails',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='get_prop_bet_emails',
            field=models.BooleanField(default=True),
        ),
    ]
