# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20170115_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedbet',
            options={'ordering': ['accepted_prop__end_date'], 'verbose_name': 'Accepted Bet'},
        ),
    ]
